### ISSUE TITLE
Feature request: app lock (single-app mode) and disabled touch buttons (back, home, search)

### ISSUE THREAD

**Issue by chrwick** [ms-iot/virtual-shields-universal#16]
I would like to use a Windows phone as control panel on the wall.

However, external people would be able to access this control panel and could quit the app by using the touch buttons. Furthermore, they could change settings.

1)
Is it possible in Windows 10 mobile to disable the touch buttons? Ideally it would be completely hidden so the remaining screen area is available for drawing.
For example, in Android it is possible to hide the touch buttons and even the top status bar.

2)
Or is there anoher method to lock-in the user in the app like the iOS guided access?

**Comment by chrwick** [comment]
Just a small update.
It seems to be possible already to put the Windows phone in a kiosk mode.
This is called "assigned access".
http://blogs.technet.com/b/tune_in_to_windows_intune/archive/2014/10/03/windows-phone-8-1-in-kiosk-mode-assigned-access-using-intune-and-configmgr.aspx
https://technet.microsoft.com/en-us/windows/dn771708.aspx

However, I do not know all the tools that are required to setup the phone for this access type.
On a normal Windows 8.1 PC it is pretty easy to setup the assigned access though.

**Comment by ooeygui** [comment]
Adding Documentation to the readme for Kiosk mode would be a good thing. Thanks!

**Comment by brunolewin** [comment]
Thanks @chrwick. Did you try either? I'm about to try the Intune option and will report back.

**Comment by JimGaleForce** [comment]
This is planned - up until recent Win10 phone builds, kiosk mode was not working. Do have a task to add shortly - however - any research toward this (i.e. did it work?) would be helpful. Thanks!

**Comment by chrwick** [comment]
@brunolewin: I will try it with the Windows phone 8.1 emulator first.

**Comment by JimGaleForce** [comment]
any update - did it work for you as expected?

**Comment by IoTGirl** [comment]
Closing Stale - No response from poster in more than a year
