### ISSUE TITLE
Sensors crashing app

### ISSUE THREAD

**Issue by sidwarkd** [ms-iot/virtual-shields-universal#26]
The compass and light sensors cause the app to crash on a Lumia 950. When I tested on a phone that did not have a compass or light sensor everything runs fine and the app reports that those capabilities are not present.

**Comment by sandervandevelde** [comment]
I had some problems with sensors too. It seems some the public XYZ New(double x, double y, double z, double w) expects all 4 values where some sensors only provide 1 or 2 values. 

`        public XYZ New(double x, double y, double z, double w)
        {
            var item = this; //ew XYZ() { Source = Source, Data = Data, Name = Name, Tag = Tag };

            if (this.Delta > 0
                  && IsWithinDelta(x, item.Data[0].Value)
                  && (item.Data.Count() < 2 || IsWithinDelta(y, item.Data[1].Value))
                  && (item.Data.Count() < 3 || IsWithinDelta(z, item.Data[2].Value))
                  && (item.Data.Count() < 4 || IsWithinDelta(w, item.Data[3].Value)))
            {
                IsChanged = false;
                return this; //no change
            }

            IsChanged = true;

            item.Data[0].Value = x;

            if (item.Data.Count() > 1)
            {
                item.Data[1].Value = y;
            }

            if (item.Data.Count() > 2)
            {
                item.Data[2].Value = z;
            }

            if (item.Data.Count() > 3)
            {
                item.Data[3].Value = w;
            }

            item.Data.Refresh();

            return item;
        }`

seems more stable.

**Comment by IoTGirl** [comment]
Closing Stale - Source is available for edit/modification as needed - no post from originator or owner for more than a year.
