### ISSUE TITLE
Shield: multiple references to missing function "'InitializeComponent()"

### ISSUE THREAD

**Issue by bryanschremp** [ms-iot/virtual-shields-universal#8]
The build fails with multiple errors (Ignore the "2013" path, I am using VS 2015):
Severity	Code	Description	Project	File	Line
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\App.xaml.cs	56
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\MainPage.xaml.cs	88
Error	CS1061	'SettingsPage' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'SettingsPage' could be found (are you missing a using directive or an assembly reference?)	Shield	C:\Users\Bryan\OneDrive\Visual Studio 2013\Projects\virtual-shields-universal\Shield\SettingsPage.xaml.cs	57

**Comment by MikaelSoderstrom** [comment]
I had that problem after cloning the repository and changing the platform SDK version. The solution was to remove some zero-width space characters in some of the XAML files.

My pull request (#7) contains updated XAML files that should allow the project to compile.
